name: Hello World Pipeline

on:
  push:
    branches: [ master ]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello, this pipeline ran because you pushed to master!"

      - name: check required files exist
        run: |
          if [ ! -f README.md ]; then
            echo "ERROR: README.md is missing!"
            exit 1
          fi
            echo "README.md found."

      - name: Show README content
        run: cat README.md

